website/views.py
import imp
from flask import (
    Blueprint, render_template, url_for, request
)
import util

views = Blueprint('views', __name__)

# credidatials
username = 'me'
password = 'test'
host = '127.0.0.1'
port = '5432'
database = 'KybPartPickerInventory'


@views.route('/')
@views.route('/base.html')
def home():
    return render_template("base.html", title="Keyboard Part Picker")

@views.route('/bulidGuide.html')
def bulid_guide():
    pcb = '''
        The PCB is the most important part of the keyboard. It is what gives the keyboard life. When trying to come up with a build,
        there are centain sizes of PCB that we recommend to stick to, 60 % , 75%, 80 % , 90%, and 100%. 
        The reason for this is that these sizes have the most support and components on the market right now. In addition 
        to thinking about the size of the PCB, you must think about the type of PCB you want for your build. 
        For the beginner level, we suggest a Hot-Swappable PCB as there 
        is no soldering at all. If you fancy yourself handy with electronics then you can either go for a 
        Standard PCB or a Through-hole PCB. The Standard only requires you to solder the switches and the 
        Through-hole requires you to solder everything from diodes to the USB connector.
        '''

    case = '''
        The Case is what holds all of the components and is one of the main factors that contributes the the
        sound generated from a keyboard. Cases come in many type of material such as plastic, wood, carbon
        fiber, aluminium, etc. As such whatever case you do choose will be impacted by whatever size of PCB you decide 
        on so be wary when making this decision.
        '''

    plate = '''
        MAJOR NOTE: If you get 5-pin switches, a plate may not be necessary as these can be used for purely PCB mounted switch builds.
        The Plate is a key component in how it will act together with the PCB and the Switches. It is a guard between the two so that if 
        you were heavy-handed, your key presses would not affect the structure of the PCB. Plates are made in accompaniment with PCB's so
        specific plates will only align with specific PCB's. Therefore, much like the case, the plate is also reliant on what choice of PCB
        you have made. As for what plates are made of, they are generally going to be composed of aluminum, brass, polycarbonate, and carbon fiber.
    '''

    stabilizers = '''             
      Stabilizers are an auxillary part when it comes to a keyboard, but it is still vital to the functionality of the entire board.
      They are a part that is essential when trying to have your keyboard sound good as well as keeping larger keys like SHIFT, ENTER, 
      CTRL, and Spacebar stable.
      '''

    switches = '''
    The Switches are what interact with the PCB to make your key presses happen. Switches are made of a housing which can have 5 or 3 pins,
    a spring that varies in weight to give the switch a particular feel, and the stem which works with the spring and housing to determine 
    what feel and sound the switch will produce. With switches there are three profiles that you can choose from, these are based on the sound 
    and feeling that they create. There is Linear which is where the switch is quieter and the press is smooth with little to no feedback, Tactile 
    which gives you a bit of press feedback and some sound, and Clicky which focuses on giving you press feedback and a particularly "clicky" sound.
    '''

    keycaps = ''' 
        The Keycaps are the primary aesthetic builder when it comes to keyboard building. They are what makes you keyboard look good and are generally
        what theme or personality your build has. When finding keycaps, it is important that you know which kind of layout your PCB is set in. There are 
        two layouts that you as a builder/hobbyist will need to keep in mind, ANSI and ISO. The main difference between the two is the Enter key, but there 
        other minor differences as well. For an ANSI board the Enter key is a normal rectangle whereas for an ISO board the Enter is an upside-down "L". 
        In addition to layout, keycaps are offered in different material and profiles. The materials they are made of determine their feel and look and the
        profile they have determine the flatness or concavity of the keycap. 
    '''

    images = ['img/pcb.jpeg', 'img/case.jpeg', 'img/plate.jpeg',
              'img/stabs.jpeg', 'img/switches.jpeg', 'img/kcps.jpeg']
    paragraph = [pcb, case, plate, stabilizers, switches, keycaps]
    return render_template("bulidGuide.html", title="Build Guide", paragraph=paragraph, images=images)



@views.route('/bulidPage.html')
def bulid_page():
    return render_template("bulidPage.html", title="Build Page",)


@views.route('/teamMem.html')
def team_member():
    return render_template("teamMem.html", title="Team Member Page",)

@views.route('/tutor.html')
def tutor():
    return render_template("tutor.html", title="Tutor",)

@views.route('partsSelection/pcb.html')
def pcb():
    cursor, connection = util.connect_to_db(
        username, password, host, port, database)
    # execute SQL commands
    record = util.fetch_case(
        cursor, sql_string="select pcb_name, pcb_url, pcb_price from product_pcb;")
    if record == -1:
        print('Something is wrong with the SQL command')
    else:
        # this will return all column names of the select result table
        # col_names = [desc[0] for desc in cursor.description]
        # only use the first five rows
        # log = record[10]
        #  print("test”)I
        log = []
        for i in record:
            log.append(i)

        # log=[[1,2],[3,4]]
    # disconnect from database
    # print('Works')
    util.disconnect_from_db(connection, cursor)
    
    return render_template("partsSelection/pcb.html", title="PCB Page", pcb_name=log)


@views.route('partsSelection/case.html', methods=('GET', 'POST'))
def case():
    cursor, connection = util.connect_to_db(
        username, password, host, port, database)
    # execute SQL commands
    record = util.fetch_case(
        cursor, sql_string="select case_name, case_url, case_price from product_case;")
    if record == -1:
        print('Something is wrong with the SQL command')
    else:
        # this will return all column names of the select result table
        # col_names = [desc[0] for desc in cursor.description]
        # only use the first five rows
        # log = record[10]
        #  print("test”)I
        log = []
        index = 0
        for i in record:
            log.append(i)
            # index +=1

    if request.method == 'POST':
        index = request.form['index']
        print("request")
        # log=[[1,2],[3,4]]
    # disconnect from database
    # print('Works')
    util.disconnect_from_db(connection, cursor)
    return render_template("partsSelection/case.html", title="Case Page", case_name=log, index =index)


@views.route('partsSelection/plate.html')
def plate():
    cursor, connection = util.connect_to_db(
        username, password, host, port, database)
    # execute SQL commands
    record = util.fetch_case(
        cursor, sql_string="select plate_name, plate_url , plate_price from product_plate;")
    if record == -1:
        print('Something is wrong with the SQL command')
    else:
        # this will return all column names of the select result table
        # col_names = [desc[0] for desc in cursor.description]
        # only use the first five rows
        # log = record[10]
        #  print("test”)I
        log = []
        for i in record:
            log.append(i)

        # log=[[1,2],[3,4]]
    # disconnect from database
    # print('Works')
    util.disconnect_from_db(connection, cursor)
    return render_template("partsSelection/plate.html", title="Plate Page", plate_name=log)


@views.route('partsSelection/stabilizers.html')
def stabilizers():
    cursor, connection = util.connect_to_db(
        username, password, host, port, database)
    # execute SQL commands
    record = util.fetch_case(
        cursor, sql_string="select stabilizer_name, stabilizer_url ,stabilizer_price from product_stabilizers;")
    if record == -1:
        print('Something is wrong with the SQL command')
    else:
        # this will return all column names of the select result table
        # col_names = [desc[0] for desc in cursor.description]
        # only use the first five rows
        # log = record[10]
        #  print("test”)I
        log = []
        for i in record:
            log.append(i)

        # log=[[1,2],[3,4]]
    # disconnect from database
    # print('Works')
    util.disconnect_from_db(connection, cursor)
    return render_template("partsSelection/stabilizers.html", title="Stabilizers Page",stabilizer_name=log)


@views.route('partsSelection/switches.html')
def switches():
    cursor, connection = util.connect_to_db(
        username, password, host, port, database)
    # execute SQL commands
    record = util.fetch_case(
        cursor, sql_string="select switches_name, switches_url , switches_price from product_switches;")
    if record == -1:
        print('Something is wrong with the SQL command')
    else:
        # this will return all column names of the select result table
        # col_names = [desc[0] for desc in cursor.description]
        # only use the first five rows
        # log = record[10]
        #  print("test”)I
        log = []
        for i in record:
            log.append(i)

        # log=[[1,2],[3,4]]
    # disconnect from database
    # print('Works')
    util.disconnect_from_db(connection, cursor)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tutor Bridge</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='baseStyle.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</head>

<body>

    {% include 'navBar.html' %}

    <div class="container-xl mx-auto py-5 position-absolute top-50 start-50 translate-middle">
        <div class="row g-2 py-5">
            <div class="col-sm-6 mx-auto text-center" style="background-color: #5467d2;">
                
                <h3 class="py-3"> Teacher </h3>
                <p>KBDpartpicker is a website catered to both beginners and enthusiasts alike! It is our goal to
                    introduce
                    and make getting into the hobby of keyboard building as seamless a process as possible. If you are a
                    newcomer,
                    we suggest you click the “Build Guide” button on the navigation bar, otherwise if you are ready to
                    get to building,
                    feel free to click on the “Start a build” button. Either way, enjoy, and we hope you stick with it.
                </p>

                <div class="container-xl mx-auto">
                    <button class="btn btn-dark me-2 text-white" style="background-color: #237405;" type="button"
                        onclick="window.location.href='tutor.html'"> Start</button>
                </div>
            </div>

            <div class="col-sm-6 mx-auto text-center" style="background-color: #5467d2;">
                <h3 class="py-3"> Student </h3>
                <p>KBDpartpicker is a website catered to both beginners and enthusiasts alike! It is our goal to
                    introduce
                    and make getting into the hobby of keyboard building as seamless a process as possible. If you are a
                    newcomer,
                    we suggest you click the “Build Guide” button on the navigation bar, otherwise if you are ready to
                    get to building,
                    feel free to click on the “Start a build” button. Either way, enjoy, and we hope you stick with it.
                </p>

                <div class="container-xl mx-auto">
                    <button class="btn btn-dark me-2 text-white" style="background-color: #237405;" type="button"
                        onclick="window.location.href='bulidPage.html'"> Start</button>
                </div>
            </div>

           

        </div>
    </div>



</body>


</html>

website/templates/bulidGuide.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KDBPartPicker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='baseStyle.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</head>

<body>
    {% include 'navBar.html' %}

    <div class="col-sm-6 mx-auto text-center py-5">
        <p>
            With keyboard buliding there are really only six major component that arenecessary for a standard build. 
            These parts are as follows; A PCB, A Case, A Plate, a setof Stabilizers, a set of switches, and a set keycaps. 
            There are of course other components. But those are mainly for aesthetics or for the board to make a better sound. 
            These would be items like pcb-plate foam, pcb-case foam, LED's, LED diffusers, aviator USB cables, gasket mount band, 
            risers etc. We hope that the following part guide will help you on your quest and Happy Building!
        </p>
    </div>

    <div class="col-lg-12 mx-auto text-center py-3 bg-success text-white">
        <h1>Components</h1>
    </div>

    {% for i in range(6) %}
    <div class="container-xl mx-auto ">
        <div class="row g-2">
            <div class="col-sm-3 mx-auto text-center">
                <img class="img-fluid w-75 p-4 rounded-3" src="{{ url_for('static', filename=images[i])}}" alt="images">
            </div>
            <div class="col-sm-9 mx-auto ps-5 text-center">
                <p class="py-5"> {{paragraph[i]}} </p>
            </div>
        </div>
    </div>
    {% endfor %}

</body>

</html>

website/templates/bulidPage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KDBPartPicker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='baseStyle.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</head>

<body>
    {% include 'navBar.html' %}


    <div class="container py-5 text-center">
        <div class="col-lg-12 mx-auto text-center py-2 bg-success text-white">
            <h1>Select Build</h1>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-light border-dark py-5">
                <thead class="thead-dark">
                    <tr>
                        <th>Components</th>
                        <th>Selection</th>
                        <th>Price</th>
                        <th>URL</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>PCB</td>
                        <td>
                            <button class="btn btn-dark me-2 text-white" style="background-color: #237405;"
                                type="button" onclick="window.location.href=' {{ url_for('views.pcb') }} '"> + Select
                            </button>
                        </td>
                        <td>PRICE/ITEM</td>
                        <td>WHERE/ITEM</td>
                    </tr>
                    <tr>
                        <td>Case</td>
                        <td>
                            <button class="btn btn-dark me-2 text-white" style="background-color: #237405;"
                                type="button" onclick="window.location.href=' {{ url_for('views.case') }} '"> + Select
                            </button>
                        </td>
                        <td>PRICE/ITEM</td>
                        <td>WHERE/ITEM</td>
                    </tr>
                    <tr>
                        <td>Plate</td>
                        <td>
                            <button class="btn btn-dark me-2 text-white" style="background-color: #237405;"
                                type="button" onclick="window.location.href=' {{ url_for('views.plate') }} '"> + Select
                            </button>
                        </td>
                        <td>PRICE/ITEM</td>
                        <td>WHERE/ITEM</td>
                    </tr>
                    <tr>
                        <td>Stabilizers</td>
                        <td>
                            <button class="btn btn-dark me-2 text-white" style="background-color: #237405;"
                                type="button" onclick="window.location.href=' {{ url_for('views.stabilizers') }} '"> +
                                Select
                            </button>
                        </td>
                        <td>PRICE/ITEM</td>
                        <td>WHERE/ITEM</td>
                    </tr>
                    <tr>
                        <td>Switches</td>
                        <td>
                            <button class="btn btn-dark me-2 text-white" style="background-color: #237405;"
                                type="button" onclick="window.location.href=' {{ url_for('views.switches') }} '"> +
                                Select
                            </button>
                        </td>
                        <td>PRICE/ITEM</td>
                        <td>WHERE/ITEM</td>
                    </tr>
                    <tr>
                        <td>Keycaps</td>
                        <td>
                            <button class="btn btn-dark me-2 text-white" style="background-color: #237405;"
                                type="button" onclick="window.location.href=' {{ url_for('views.keycaps') }} '"> +
                                Select
                            </button>
                        </td>
                        <td>PRICE/ITEM</td>
                        <td>WHERE/ITEM</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

</body>


</html>

website/templates/currentBulid.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KDBPartPicker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='baseStyle.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</head>

<body>
    {% include 'navBar.html' %}


    <div class="container py-5 text-center">
        <div class="col-lg-12 mx-auto text-center py-2 bg-success text-white">
            <h1>Select Build</h1>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-light border-dark py-5">
                <thead class="thead-dark">
                    <tr>
                        <th>Components</th>
                        <th>Selection</th>
                        <th>Price</th>
                        <th>URL</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>PCB</td>
                        <td>
                            DZ60 Soldered 60% Mechanical Keyboard PCB
                        </td>
                        <td>$38.00</td>
                        <td>                        
                            <a href="https://kbdfans.com/collections/pcb/products/dz60-60-pcb">Link</a>
                        </td>

                    </tr>
                    <tr>
                        <td>Case</td>
                        <td>
                            <p>KBDFANS 5° 60% E-White CASE    </p>
                        </td>
                        <td>$79.00                        </td>
                        <td>                       
                             <a href="https://kbdfans.com/collections/case/products/kbdfans-5-60-e-white-case ">Link</a>
                        </td>


                    </tr>
                    <tr>
                        <td>Plate</td>
                        <td>
                            60% Brass ANSI Plate
                        </td>
                        <td>$39.90</td>

                        <td>                       
                            <a href="https://kbdfans.com/collections/plate/products/brass-60-plate">Link</a>
                       </td>
                    </tr>
                    <tr>
                        <td>Stabilizers</td>
                        <td>
                            Everglide V2 Transparent Gold Plated Pcb screw in Stabilizer for Custom Mechanical Keyboard gh60 xd64 xd84 6.25x 2x xd96 xd87 
                        </td>
                        <td> $23.90</td>
                        <td>                       
                            <a href="https://kprepublic.com/collections/stabilizer/products/everglide-v2-transparent-gold-plated-pcb-screw-in-stabilizer-for-custom-mechanical-keyboard-gh60-xd64-xd84-6-25x-2x-xd96-xd87 ">Link</a>
                       </td>

                    </tr>
                    <tr>
                        <td>Switches</td>
                        <td>
                            Cherry MX Hyperglide Milk Tactile Switches    
                        </td>
                        <td>$3.50</td>

                        <td>                       
                            <a href="https://kbdfans.com/collections/switches/products/cherry-mx-hyperglide-milk-tactile-switches ">Link</a>
                       </td>
                    </tr>
                    <tr>
                        <td>Keycaps</td>
                        <td>
                            EPBT ABS Doubleshot Blue and White Mechanical Keyboard Keycaps Set   
                        </td>
                        <td>$69.00                        </td>

                        <td>                       
                            <a href="https://kbdfans.com/collections/keycaps/products/epbt-abs-doubleshot-blue-and-white-mechanical-keyboard-keycaps-set  ">Link</a>
                       </td>

                    </tr>
                </tbody>
            </table>
        </div>
    </div>

</body>


</html>

website/templates/navBar.html
<nav class="navbar navbar-light" style="background-color: rgb(97, 186, 64);">
    <form class="container-fluid justify-content-start">
        <!-- <h5>Keyboard Part Picker</h5> -->
        <a class="navbar-brand" href="#" onclick="window.location.href='{{ url_for('views.home') }}'">
            <!-- <img  alt="" width="30" height="24" -->
            <!-- class="d-inline-block align-text-top" "> -->
            Tutor Bridge
        </a>
        <button class="btn btn-dark me-2 text-white" style="background-color: #237405;" type="button"
            onclick="window.location.href='{{ url_for('views.bulid_guide')}}'">Build Guide
        </button>
        <button class="btn btn-dark me-2 text-white" style="background-color: #237405;" type="button"
            onclick="window.location.href=' {{ url_for('views.current_bulid') }}'">Current Build
        </button>
        <button class="btn btn-dark me-2 text-white" style="background-color: #237405;" type="button"
            onclick="window.location.href='{{url_for('views.team_member')}}'">Team Members
        </button>
        
    </form>
</nav>

website/templates/teamMem.html
<!DOCTYPE html>
<html lang="en">
<title>Team Members</title>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KDBPartPicker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='baseStyle.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>



<body>

    {% include 'navBar.html' %}

    <!-- <div class="container-xl mx-auto py-5 position-absolute top-50 start-50 translate-middle"> -->
        <!-- <div class="row g-2 py-5"> -->

            <!-- <div class="col-lg-1 "></div> -->
                

            <div class="container-xl text-center border border-primary border-5  mt-5">
                <!-- <h3 class="p-3" style="background-color: #6d8edbc5;" > Miriam Harb </h3> -->
                <div class="container-xl">
                    <h3 class="p-3"  > Miriam Harb </h3>

                    <p>
                        Developed the Team Member Page
                        Converted some of th JSON files<br>into CSV files with Arturo
                        Wrote SQL commands to add columns to the database with Arturo
                    </p>
                </div>
            </div>

            <!-- <div class="col-lg-1 "></div> -->

            <div class="container-xl text-center border border-primary border-5   mt-5 ">
                <h3 class="p-3" > Jan Andre Verceles-Zara </h3>
                <div class="container-xl ">
                    <p>
                        Designed all frontend pages except the Team Member page
                        Scraped the data for the datasets into JSON files
                        Cleaned code and found the image assets for site
                        Filled out the Build Guide Page</li>
                        Helped add code to populate pages with data from the database</li>
                    </p>
                </div>
            </div>


            <div class="container-xl text-center border border-primary border-5  mt-5 " >
                <h3 class="p-3"> Arturo Calderon </h3>
                <div class="container-xl ">
                    <!-- <p> -->
                        Developed all frontend pages except the Team Member page</li>
                        Converted some of th JSON files into CSV files</li>
                        Wrote SQL commands to add columns to the database with Arturo</li>
                    <!-- </p> -->
                </div>
            </div>


           
        <!-- </div> -->
    <!-- </div> -->

</body>


</html>

website/templates/tutor.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KDBPartPicker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='baseStyle.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</head>

<body>
    {% include 'navBar.html' %}

    <div class="col-sm-6 mx-auto text-center py-5">
        <!-- <h1>Tutor Now</h1> -->
    </div>

    <div class="col-lg-12 mx-auto text-center py-3 bg-success text-white">
        <h1>Tutor</h1>
    </div>

    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Dropdown button
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
        </div>
    </div>

    <div class="col-lg-12 mx-auto text-center py-3 bg-success text-white">

        <div class="mb-3 row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="email@example.com">
            </div>
        </div>
        <div class="mb-3 row">
            <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="inputPassword">
            </div>
        </div>
    </div>


</body>

</html>